apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: samupif/sales-notifier:latest
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: sales-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
