apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-generator
  template:
    metadata:
      labels:
        app: pdf-generator
    spec:
      containers:
        - name: pdf-generator
          image: samupif/sales-pdf-generator:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: sales-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
